# -*- coding: utf-8 -*-
"""TestesProRasp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Ler3oLvMvdm0P6EBDFUyTQaDPRR8LB9
"""

import sqlite3
import time

'''
  @TODO 
    - verificar se dtype é válido
'''

def create_table():
  conn = sqlite3.connect('data.db')
  curs = conn.cursor()

  curs.execute("""
    CREATE TABLE IF NOT EXISTS data (
      ID_DATA INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
      END_DEVICE_NAME TEXT NOT NULL,
      DTYPE TEXT NOT NULL,
      VALUE REAL,
      DATE_CREATED DATE NOT NULL
    );
  """)

  conn.commit()
  conn.close()


def insert(device_name, dtype, valor):
  conn = sqlite3.connect('data.db')
  curs = conn.cursor()

  curs.execute(f"INSERT INTO data (END_DEVICE_NAME, DTYPE, VALUE, DATE_CREATED) VALUES ('{device_name}', '{dtype}', {valor}, datetime('now'))")

  conn.commit()
  conn.close()
  ## @TODO return true ou false
  return curs.lastrowid


def consultaLastRecord(device_name):
  conn = sqlite3.connect('data.db')
  curs = conn.cursor()

  query = f"SELECT END_DEVICE_NAME, DTYPE, VALUE, max(DATE_CREATED) from data WHERE END_DEVICE_NAME = '{device_name}' group by DTYPE"
  curs.execute(query)
  results = curs.fetchall()
  result_dict = []

  for row in results:
    row_dict = {}
    for i, col in enumerate(curs.description):
      row_dict[col[0]] = row[i]
    result_dict.append(row_dict)

  conn.commit()
  conn.close()
  return result_dict
 



create_table()
insert('PAI', 'pH', 10.0)
time.sleep(1)
insert('PAI', 'Conduct', 5.0)
time.sleep(1)
insert('PAI', 'pH', 11.0)
time.sleep(1)
insert('PAI', 'pH', 25.0)
insert('PAI', 'Conduct', 42.0)
insert('PAI', 'Temperature', 12.0)

lastRecord = consultaLastRecord('PAI')

for v in lastRecord:
  print('Dtype: ', v['DTYPE'], ' e valor: ', v['VALUE'])

# -*- coding: utf-8 -*-
"""alimentandoFirebase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkFSKcWsT2YyVBKaFVkVMvUqln65N3cI
"""

#!pip install firebase
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from firebase import firebase
import datetime
import random
import time
import json

FB_URL="https://testemonit-b47a7-default-rtdb.firebaseio.com"

def feedFb(dtype, valor):
    global FB_URL
    firebaseApp = firebase.FirebaseApplication(FB_URL, None)
  
    data = {dtype: valor,
            'time_created': datetime.datetime.now()}
    result = firebaseApp.post('/Pai/Sensor/'+dtype+'/', data)
    print("Firebase post result: \n\t")
    print(result)

    time.sleep(5)

def feedFbLastRecord(device_name):
  global FB_URL
  lastRecord = consultaLastRecord(device_name)
  dataToSend = {}

  firebaseApp = firebase.FirebaseApplication(FB_URL, None)
  
  for v in lastRecord:
    dataToSend[v['DTYPE']] = v['VALUE']

  result = firebaseApp.put('/'+device_name+'/', name='LastRecord', data=dataToSend)
  print("Firebase post result: \n\t")
  print(result)

#feedFb('pH',15)
#feedFb('Conduct',20)
insert('PAI', 'Temperature', 29.0)
insert('PAI', 'Temperature', 29.0)
feedFbLastRecord('PAI')